### ISSUE TITLE
Questions on input type/method

### ISSUE THREAD

**Issue by kvbulusu** [just-ai/aimybox-android-assistant#48]
I'm new to android and a newbie qn. Along with voice, how can I add a text so users can type too?  In your example/demo code what should I change?  I want to have both voice and text... I'm using rasa nlu stack....

**Comment by morfeusys** [comment]
You have to implement text input UI on your side and add it to your application. Once the user inputs some text, it should be passed to send() method of Aimybox. All other work will be done under the hood.
